spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: Welcome@123
    url: jdbc:mysql://47.92.55.53:3306/wx1_db?serverTimezone=UTC&userUnicode=true&characterEncoding=utf-8
    driver‐class‐name: com.mysql.jdbc.Driver
    #Spring Boot 默认是不注入这些属性值的，需要自己绑定
    #druid 数据源专有配置
    initialSize: 5
    minIdle: 5
    maxActive: 15
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false

server:
  port: 80

#ging:
#  config: classpath:4j.properties
#  level:
mybatis:
  mapper-locations: classpath:mapper/*.xml