spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: Welcome@123
    url: jdbc:mysql://47.92.55.53:3306/wx1_db?serverTimezone=UTC&userUnicode=true&characterEncoding=utf-8
    driver‐class‐name: com.mysql.jdbc.Driver
server:
  port: 80

#logging:
#  config: classpath:log4j.properties
#  level:
mybatis:
  mapper-locations: classpath:mapper/*.xml